# Generated by Django 5.0.7 on 2024-08-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("pickup_address", models.CharField(max_length=255)),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255)),
                ("current_address", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("weight", models.PositiveIntegerField()),
                ("pickup_date", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit-card", "Credit Card"),
                            ("debit-card", "Debit Card"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_details", models.CharField(max_length=255)),
                (
                    "signature",
                    models.FileField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
