# Generated by Django 5.0.7 on 2024-08-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0004_alter_shipmentbooking_date_alter_userprofile_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="img",
        ),
        migrations.AddField(
            model_name="shipmentbooking",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentbooking",
            name="current_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentbooking",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shipmentbooking",
            name="payment_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentbooking",
            name="pickup_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="shipmentbooking",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.AlterField(
            model_name="shipmentbooking",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
