# Generated by Django 5.0.7 on 2024-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0006_alter_shipmentbooking_pickup_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=255)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email",
                    models.EmailField(default="no-reply@example.com", max_length=254),
                ),
                (
                    "pickup_address",
                    models.CharField(default="Not provided", max_length=255),
                ),
                (
                    "from_address",
                    models.CharField(default="Not provided", max_length=255),
                ),
                (
                    "to_address",
                    models.CharField(default="Not provided", max_length=255),
                ),
                (
                    "current_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(default="No description provided")),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("pickup_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit-card", "Credit Card"),
                            ("debit-card", "Debit Card"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        default="credit-card",
                        max_length=20,
                    ),
                ),
                ("payment_details", models.TextField(blank=True, null=True)),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ShipmentBooking",
        ),
    ]
