# Generated by Django 5.0.7 on 2024-09-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0009_alter_person_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="date",
            new_name="date_created",
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="person",
            name="from_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="pickup_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="to_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
