# Generated by Django 5.0.7 on 2024-10-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0012_person_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="Order_Id",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("Transit", "Transit"),
                    ("processing", "Processing"),
                    ("Cleared", "Cleared"),
                    ("Detained", "Detained"),
                    ("Despatched", "Despatched"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
