# Generated by Django 5.0.7 on 2024-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0013_alter_person_order_id_alter_person_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="Order_Id",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
