# Generated by Django 5.0.7 on 2024-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0015_alter_person_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="agent_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("delivery_agent", "Delivery Agent")],
                default="user",
                max_length=20,
            ),
        ),
    ]
