# Generated by Django 5.0.7 on 2024-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0016_userprofile_agent_id_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="Order_Id",
        ),
        migrations.AlterField(
            model_name="person",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("transit", "Transit"),
                    ("processing", "Processing"),
                    ("cleared", "Cleared"),
                    ("detained", "Detained"),
                    ("despatched", "Despatched"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="order_id",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
