# Generated by Django 5.0.7 on 2024-10-23 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0017_remove_person_order_id_alter_person_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]
