# Generated by Django 5.0.7 on 2024-10-23 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0018_remove_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="loc",
        ),
    ]
