# Generated by Django 5.0.7 on 2024-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0019_remove_userprofile_loc"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
            preserve_default=False,
        ),
    ]
