# Generated by Django 5.0.7 on 2024-10-23 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0020_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="agent_id",
        ),
    ]
