# Generated by Django 5.0.7 on 2024-10-23 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0021_remove_userprofile_agent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_number",
        ),
    ]
