# Generated by Django 5.0.7 on 2024-10-24 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0023_agentprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentprofile",
            name="user",
        ),
    ]
