# Generated by Django 5.0.7 on 2024-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0024_remove_agentprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="password",
            field=models.CharField(default="*********", max_length=50),
        ),
    ]
