# Generated by Django 5.0.7 on 2024-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0025_agentprofile_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprofile",
            name="password",
            field=models.CharField(default="Default", max_length=50),
        ),
    ]
