# Generated by Django 5.0.7 on 2024-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0026_alter_agentprofile_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.AddField(
            model_name="person",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="Processing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit-card", "Credit Card"),
                    ("debit-card", "Debit Card"),
                    ("Upi", "Upi"),
                    ("other", "Other"),
                ],
                default="credit-card",
                max_length=20,
            ),
        ),
    ]
