# Generated by Django 5.0.7 on 2024-11-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0028_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                max_length=10,
            ),
        ),
    ]
