# Generated by Django 5.0.7 on 2024-11-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0032_person_shipmentsteps_delete_shipmentstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="Shipmentsteps",
            field=models.IntegerField(
                choices=[
                    (1, "Ordered"),
                    (2, "Shipped"),
                    (3, "Out for Delivery"),
                    (4, "Delivered"),
                ],
                default=1,
            ),
        ),
    ]
