# Generated by Django 5.0.7 on 2024-11-11 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0033_alter_person_shipmentsteps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="Shipmentsteps",
        ),
    ]
