# Generated by Django 5.0.7 on 2024-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0034_remove_person_shipmentsteps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit-card", "Credit Card"),
                    ("debit-card", "Debit Card"),
                    ("upi", "UPI"),
                    ("other", "Other"),
                ],
                default="credit-card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
